package com.incident;

public enum IncidentType {
    DB_CONNECTION_LOST, DB_QUERY_ERROR, DB_CORRUPTION_SUSPECTED,
    UNAUTHORIZED_ACCESS_SUSPECTED, SYSTEM_CRASH,
    BACKUP_FAILED, BACKUP_SUCCEEDED, RESTORE_PERFORMED, RESTORE_FAILED,
    BACKUP_CLOUD_UPLOAD_SUCCEEDED, BACKUP_CLOUD_UPLOAD_FAILED,
    CONFIG_ERROR, SECURITY_CHECK_FAILED, OTHER
}